language: python
cache: pip

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          sudo: true
          env: TOXENV=py37
        - python: 3.8
          sudo: true
          env: TOXENV=py38

install:
  - pip install tox

script:
  - tox

dist: xenial
